import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata} from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Экспорт viewport без импорта типа — работает корректно и добавляет нужный мета-тег
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Sidebar />
        {children}
        </body>
    </html>
  )
}
